### ISSUE TITLE
node.xml missing from tomcat installation

### ISSUE THREAD

**Issue by simesy** [entermedia-community/entermediadb-installers#1]
There is an issue in the /usr/bin/entermediadb script, tested on Ubuntu 15.10. After installing a site, the app gives this error:

```

org.openedit.OpenEditException: WEB-INF/node.xml is not defined
	at org.entermediadb.asset.cluster.BaseNodeManager.getLocalNode(BaseNodeManager.java:88)
	at org.entermediadb.elasticsearch.ElasticNodeManager.getClient(ElasticNodeManager.java:125)
	at org.entermediadb.elasticsearch.searchers.BaseElasticSearcher.getClient(BaseElasticSearcher.java:150)
	at org.entermediadb.elasticsearch.searchers.BaseElasticSearcher.searchByField(BaseElasticSearcher.java:1447)
	at org.openedit.data.BaseSearcher.searchById(BaseSearcher.java:1891)
	at org.entermediadb.elasticsearch.searchers.ElasticListSearcher.searchById(ElasticListSearcher.java:196)
	at org.openedit.data.SearcherManager.resolveCatalogId(SearcherManager.java:454)
	at org.openedit.data.SearcherManager.getSearcher(SearcherManager.java:50)
	at org.openedit.users.BaseUserManager.getUserSearcher(BaseUserManager.java:49)
	at org.entermediadb.asset.modules.AdminModule.createUserSession(AdminModule.java:771)
	at org.entermediadb.asset.modules.AdminModule.autoLogin(AdminModule.java:737)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openedit.ModuleManager.execMethod(ModuleManager.java:107)
	at org.openedit.ModuleManager.executePageAction(ModuleManager.java:61)
	at org.openedit.ModuleManager.executePathActions(ModuleManager.java:184)
	at org.openedit.servlet.BaseOpenEditEngine.executePathActions(BaseOpenEditEngine.java:232)
	at org.openedit.servlet.BaseOpenEditEngine.beginRender(BaseOpenEditEngine.java:153)
	at org.openedit.servlet.BaseOpenEditEngine.render(BaseOpenEditEngine.java:122)
	at org.openedit.servlet.OpenEditFilter.doFilter(OpenEditFilter.java:79)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.openedit.servlet.gzip.GzipFilter.doFilter(GzipFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:136)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:74)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:526)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1017)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:652)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1575)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1533)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I experimented by manually copying node.xml from /usr/share/entermediadb/webapps/WEB-INF/node.xml into the tomcat/WEB-INF directory. This makes the error go away and the resulting error is:

```
/WEB-INF/base/_site.xconf#Admin.autoLogin blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
Browser:	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/48.0.2564.82 Chrome/48.0.2564.82 Safari/537.36 192.168.141.1
Details:	show details
 org.openedit.OpenEditException: /WEB-INF/base/_site.xconf#Admin.autoLogin blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
	at org.openedit.ModuleManager.execMethod(ModuleManager.java:119)
	at org.openedit.ModuleManager.executePageAction(ModuleManager.java:61)
	at org.openedit.ModuleManager.executePathActions(ModuleManager.java:184)
	at org.openedit.servlet.BaseOpenEditEngine.executePathActions(BaseOpenEditEngine.java:232)
	at org.openedit.servlet.BaseOpenEditEngine.beginRender(BaseOpenEditEngine.java:153)
	at org.openedit.servlet.BaseOpenEditEngine.render(BaseOpenEditEngine.java:122)
	at org.openedit.servlet.OpenEditFilter.doFilter(OpenEditFilter.java:79)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.openedit.servlet.gzip.GzipFilter.doFilter(GzipFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:136)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:74)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:526)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1017)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:652)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1575)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1533)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]
	at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:154)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.checkGlobalBlock(TransportSingleShardAction.java:97)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.<init>(TransportSingleShardAction.java:131)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.<init>(TransportSingleShardAction.java:115)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.doExecute(TransportSingleShardAction.java:87)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.doExecute(TransportSingleShardAction.java:51)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70)
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
	at org.entermediadb.elasticsearch.searchers.BaseElasticSearcher.searchByField(BaseElasticSearcher.java:1447)
	at org.openedit.data.BaseSearcher.searchById(BaseSearcher.java:1891)
	at org.entermediadb.elasticsearch.searchers.ElasticListSearcher.searchById(ElasticListSearcher.java:196)
	at org.openedit.data.SearcherManager.resolveCatalogId(SearcherManager.java:454)
	at org.openedit.data.SearcherManager.getSearcher(SearcherManager.java:50)
	at org.openedit.users.BaseUserManager.getUserSearcher(BaseUserManager.java:49)
	at org.entermediadb.asset.modules.AdminModule.createUserSession(AdminModule.java:771)
	at org.entermediadb.asset.modules.AdminModule.autoLogin(AdminModule.java:737)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openedit.ModuleManager.execMethod(ModuleManager.java:107)
	... 27 more
```

**Comment by simesy** [comment]
When I rebuilt from scratch, copied the missing file, I didn't get the second error anymore.

**Comment by fakechuck** [comment]
Thanks for the report. The node.xml should be copied from
/usr/share/entermediadb/webapp/WEB-INF to the installation location at
/your/pathto/entermediadb/webapp/WEB-INF when the "entermediadb install"
command is issued. This is because tomcat cannot follow symlinks. Somehow
this became missing from our script. I am unsure why you would be seeing
the second error if you put the node.xml in the place (next to web.xml).
Your use of "tomcat/WEB-INF" does not seem right, but I don't know what
your installation path was. Try making sure it is alongside web.xml in your
deployed app's webapp/WEB-INF, not in tomcat's folders. Hopefully this will
help.

**Comment by simesy** [comment]
yea it was webapp/WEB-INF, I mistyped. Thanks for the update
